name: vet_app
description: Flutter vet application. This is a technical test for Shamba records.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^6.0.0
  rxdart: ^0.26.0
  flutter_hooks: ^0.16.0
  hooks_riverpod: ^0.13.1
  injectable: ^1.2.0
  google_fonts: ^2.0.0
  uuid: ^3.0.1
  dio: ^4.0.0-beta6
  pinput: ^1.1.0
  flutter_platform_widgets: ^1.0.1-nullsafety.0

  #Firebase
  firebase_core: ^1.0.0
  firebase_auth: ^1.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  injectable_generator: ^1.2.0

flutter:
  uses-material-design: true
